<?php

namespace Database\Seeders;

use App\Models\Kecamatan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KecamatanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['no_camat' => '1', 'no_deskel' => '0', 'kecamatan' => 'Terara', 'deskel' => '-'],
            ['no_camat' => '1', 'no_deskel' => '1', 'kecamatan' => 'Terara', 'deskel' => 'Terara'],
            ['no_camat' => '1', 'no_deskel' => '2', 'kecamatan' => 'Terara', 'deskel' => 'Sukadana'],
            ['no_camat' => '1', 'no_deskel' => '3', 'kecamatan' => 'Terara', 'deskel' => 'Kalianyar '],
            ['no_camat' => '1', 'no_deskel' => '4', 'kecamatan' => 'Terara', 'deskel' => 'Jenggik'],
            ['no_camat' => '1', 'no_deskel' => '5', 'kecamatan' => 'Terara', 'deskel' => 'Lando '],
            ['no_camat' => '1', 'no_deskel' => '6', 'kecamatan' => 'Terara', 'deskel' => 'Rarang'],
            ['no_camat' => '1', 'no_deskel' => '7', 'kecamatan' => 'Terara', 'deskel' => 'Rarang Selatan'],
            ['no_camat' => '1', 'no_deskel' => '8', 'kecamatan' => 'Terara', 'deskel' => 'Rarang Tengah '],
            ['no_camat' => '1', 'no_deskel' => '9', 'kecamatan' => 'Terara', 'deskel' => 'Rarang Batas '],
            ['no_camat' => '1', 'no_deskel' => '10', 'kecamatan' => 'Terara', 'deskel' => 'Embung Kandong '],
            ['no_camat' => '1', 'no_deskel' => '11', 'kecamatan' => 'Terara', 'deskel' => 'Embung Raja '],
            ['no_camat' => '1', 'no_deskel' => '12', 'kecamatan' => 'Terara', 'deskel' => 'Suradadi'],
            ['no_camat' => '1', 'no_deskel' => '13', 'kecamatan' => 'Terara', 'deskel' => 'Selagik '],
            ['no_camat' => '1', 'no_deskel' => '14', 'kecamatan' => 'Terara', 'deskel' => 'Santong'],
            ['no_camat' => '1', 'no_deskel' => '15', 'kecamatan' => 'Terara', 'deskel' => 'Leming '],
            ['no_camat' => '1', 'no_deskel' => '16', 'kecamatan' => 'Terara', 'deskel' => 'Pandan Duri '],
            ['no_camat' => '2', 'no_deskel' => '0', 'kecamatan' => 'Montong Gading', 'deskel' => '-'],
            ['no_camat' => '2', 'no_deskel' => '1', 'kecamatan' => 'Montong Gading', 'deskel' => 'Pringgajurang'],
            ['no_camat' => '2', 'no_deskel' => '2', 'kecamatan' => 'Montong Gading', 'deskel' => 'Montong Betok'],
            ['no_camat' => '2', 'no_deskel' => '3', 'kecamatan' => 'Montong Gading', 'deskel' => 'Kilang'],
            ['no_camat' => '2', 'no_deskel' => '4', 'kecamatan' => 'Montong Gading', 'deskel' => 'Perian'],
            ['no_camat' => '2', 'no_deskel' => '5', 'kecamatan' => 'Montong Gading', 'deskel' => 'Jenggik Utara'],
            ['no_camat' => '2', 'no_deskel' => '6', 'kecamatan' => 'Montong Gading', 'deskel' => 'Pringgajurang Utara '],
            ['no_camat' => '2', 'no_deskel' => '7', 'kecamatan' => 'Montong Gading', 'deskel' => 'Pesanggrahan '],
            ['no_camat' => '2', 'no_deskel' => '8', 'kecamatan' => 'Montong Gading', 'deskel' => 'Lendang Belo'],
            ['no_camat' => '3', 'no_deskel' => '0', 'kecamatan' => 'Sikur', 'deskel' => '-'],
            ['no_camat' => '3', 'no_deskel' => '1', 'kecamatan' => 'Sikur', 'deskel' => 'Semaya'],
            ['no_camat' => '3', 'no_deskel' => '2', 'kecamatan' => 'Sikur', 'deskel' => 'Darmasari '],
            ['no_camat' => '3', 'no_deskel' => '3', 'kecamatan' => 'Sikur', 'deskel' => 'Sikur'],
            ['no_camat' => '3', 'no_deskel' => '4', 'kecamatan' => 'Sikur', 'deskel' => 'Sikur Selatan '],
            ['no_camat' => '3', 'no_deskel' => '5', 'kecamatan' => 'Sikur', 'deskel' => 'Sikur Barat '],
            ['no_camat' => '3', 'no_deskel' => '6', 'kecamatan' => 'Sikur', 'deskel' => 'Montong Baan'],
            ['no_camat' => '3', 'no_deskel' => '7', 'kecamatan' => 'Sikur', 'deskel' => 'Montong Baan Selatan '],
            ['no_camat' => '3', 'no_deskel' => '8', 'kecamatan' => 'Sikur', 'deskel' => 'Loyok'],
            ['no_camat' => '3', 'no_deskel' => '9', 'kecamatan' => 'Sikur', 'deskel' => 'Gelora '],
            ['no_camat' => '3', 'no_deskel' => '10', 'kecamatan' => 'Sikur', 'deskel' => 'Kotaraja'],
            ['no_camat' => '3', 'no_deskel' => '11', 'kecamatan' => 'Sikur', 'deskel' => 'Tete Batu'],
            ['no_camat' => '3', 'no_deskel' => '12', 'kecamatan' => 'Sikur', 'deskel' => 'Tetebatu Selatan '],
            ['no_camat' => '3', 'no_deskel' => '13', 'kecamatan' => 'Sikur', 'deskel' => 'Kembang Kuning'],
            ['no_camat' => '3', 'no_deskel' => '14', 'kecamatan' => 'Sikur', 'deskel' => 'Jeruk Manis '],
            ['no_camat' => '4', 'no_deskel' => '0', 'kecamatan' => 'Masbagik', 'deskel' => '-'],
            ['no_camat' => '4', 'no_deskel' => '1', 'kecamatan' => 'Masbagik', 'deskel' => 'Kesik'],
            ['no_camat' => '4', 'no_deskel' => '2', 'kecamatan' => 'Masbagik', 'deskel' => 'Paokmotong'],
            ['no_camat' => '4', 'no_deskel' => '3', 'kecamatan' => 'Masbagik', 'deskel' => 'Masbagik Selatan'],
            ['no_camat' => '4', 'no_deskel' => '4', 'kecamatan' => 'Masbagik', 'deskel' => 'Masbagik Timur'],
            ['no_camat' => '4', 'no_deskel' => '5', 'kecamatan' => 'Masbagik', 'deskel' => 'Masbagik Utara'],
            ['no_camat' => '4', 'no_deskel' => '6', 'kecamatan' => 'Masbagik', 'deskel' => 'Masbagik Utara Baru '],
            ['no_camat' => '4', 'no_deskel' => '7', 'kecamatan' => 'Masbagik', 'deskel' => 'Danger'],
            ['no_camat' => '4', 'no_deskel' => '8', 'kecamatan' => 'Masbagik', 'deskel' => 'Kumbang '],
            ['no_camat' => '4', 'no_deskel' => '9', 'kecamatan' => 'Masbagik', 'deskel' => 'Lendang Nangka'],
            ['no_camat' => '4', 'no_deskel' => '10', 'kecamatan' => 'Masbagik', 'deskel' => 'Lendang Nangka Utara '],
            ['no_camat' => '5', 'no_deskel' => '0', 'kecamatan' => 'Pringgasela', 'deskel' => '-'],
            ['no_camat' => '5', 'no_deskel' => '1', 'kecamatan' => 'Pringgasela', 'deskel' => 'Rempung'],
            ['no_camat' => '5', 'no_deskel' => '2', 'kecamatan' => 'Pringgasela', 'deskel' => 'Pringgasela'],
            ['no_camat' => '5', 'no_deskel' => '3', 'kecamatan' => 'Pringgasela', 'deskel' => 'Jurit'],
            ['no_camat' => '5', 'no_deskel' => '4', 'kecamatan' => 'Pringgasela', 'deskel' => 'Pengadangan'],
            ['no_camat' => '5', 'no_deskel' => '5', 'kecamatan' => 'Pringgasela', 'deskel' => 'Aikdewa '],
            ['no_camat' => '5', 'no_deskel' => '6', 'kecamatan' => 'Pringgasela', 'deskel' => 'Jurit Baru '],
            ['no_camat' => '5', 'no_deskel' => '7', 'kecamatan' => 'Pringgasela', 'deskel' => 'Pringgasela Selatan '],
            ['no_camat' => '5', 'no_deskel' => '8', 'kecamatan' => 'Pringgasela', 'deskel' => 'Pengadangan Barat '],
            ['no_camat' => '5', 'no_deskel' => '9', 'kecamatan' => 'Pringgasela', 'deskel' => 'Timba Nuh '],
            ['no_camat' => '5', 'no_deskel' => '10', 'kecamatan' => 'Pringgasela', 'deskel' => 'Pringgasela Timur '],
            ['no_camat' => '6', 'no_deskel' => '0', 'kecamatan' => 'Selong', 'deskel' => '-'],
            ['no_camat' => '6', 'no_deskel' => '1', 'kecamatan' => 'Selong', 'deskel' => 'Kel. Pancor'],
            ['no_camat' => '6', 'no_deskel' => '2', 'kecamatan' => 'Selong', 'deskel' => 'Kel. Sekarteja'],
            ['no_camat' => '6', 'no_deskel' => '3', 'kecamatan' => 'Selong', 'deskel' => 'Kel. Majidi'],
            ['no_camat' => '6', 'no_deskel' => '4', 'kecamatan' => 'Selong', 'deskel' => 'Kel. Rakam'],
            ['no_camat' => '6', 'no_deskel' => '5', 'kecamatan' => 'Selong', 'deskel' => 'Kel. Sandubaya'],
            ['no_camat' => '6', 'no_deskel' => '6', 'kecamatan' => 'Selong', 'deskel' => 'Kel. Selong'],
            ['no_camat' => '6', 'no_deskel' => '7', 'kecamatan' => 'Selong', 'deskel' => 'Kel. Kelayu Selatan'],
            ['no_camat' => '6', 'no_deskel' => '8', 'kecamatan' => 'Selong', 'deskel' => 'Kel. Deggen'],
            ['no_camat' => '6', 'no_deskel' => '9', 'kecamatan' => 'Selong', 'deskel' => 'Kel. Kembang Sari'],
            ['no_camat' => '6', 'no_deskel' => '10', 'kecamatan' => 'Selong', 'deskel' => 'Kel. Kelayu Utara'],
            ['no_camat' => '6', 'no_deskel' => '11', 'kecamatan' => 'Selong', 'deskel' => 'Kel. Kelaju Jorong'],
            ['no_camat' => '6', 'no_deskel' => '12', 'kecamatan' => 'Selong', 'deskel' => 'Denggen Timur '],
            ['no_camat' => '7', 'no_deskel' => '0', 'kecamatan' => 'Labuhan Haji', 'deskel' => '-'],
            ['no_camat' => '7', 'no_deskel' => '1', 'kecamatan' => 'Labuhan Haji', 'deskel' => 'Labuhan Haji'],
            ['no_camat' => '7', 'no_deskel' => '2', 'kecamatan' => 'Labuhan Haji', 'deskel' => 'Peneda Gandor'],
            ['no_camat' => '7', 'no_deskel' => '3', 'kecamatan' => 'Labuhan Haji', 'deskel' => 'Teros'],
            ['no_camat' => '7', 'no_deskel' => '4', 'kecamatan' => 'Labuhan Haji', 'deskel' => 'Banjarsari '],
            ['no_camat' => '7', 'no_deskel' => '5', 'kecamatan' => 'Labuhan Haji', 'deskel' => 'Kertasari '],
            ['no_camat' => '7', 'no_deskel' => '6', 'kecamatan' => 'Labuhan Haji', 'deskel' => 'Kel. Tanjung'],
            ['no_camat' => '7', 'no_deskel' => '7', 'kecamatan' => 'Labuhan Haji', 'deskel' => 'Kel. Suryawangi'],
            ['no_camat' => '7', 'no_deskel' => '8', 'kecamatan' => 'Labuhan Haji', 'deskel' => 'Kel. Ijobalit'],
            ['no_camat' => '7', 'no_deskel' => '9', 'kecamatan' => 'Labuhan Haji', 'deskel' => 'Kel. Geres '],
            ['no_camat' => '7', 'no_deskel' => '10', 'kecamatan' => 'Labuhan Haji', 'deskel' => 'Korleko'],
            ['no_camat' => '7', 'no_deskel' => '11', 'kecamatan' => 'Labuhan Haji', 'deskel' => 'Korleko Selatan '],
            ['no_camat' => '7', 'no_deskel' => '12', 'kecamatan' => 'Labuhan Haji', 'deskel' => 'Tirtanadi '],
            ['no_camat' => '8', 'no_deskel' => '0', 'kecamatan' => 'Sukamulia', 'deskel' => '-'],
            ['no_camat' => '8', 'no_deskel' => '1', 'kecamatan' => 'Sukamulia', 'deskel' => 'Setanggor'],
            ['no_camat' => '8', 'no_deskel' => '2', 'kecamatan' => 'Sukamulia', 'deskel' => 'Jantuk'],
            ['no_camat' => '8', 'no_deskel' => '3', 'kecamatan' => 'Sukamulia', 'deskel' => 'Padamara'],
            ['no_camat' => '8', 'no_deskel' => '4', 'kecamatan' => 'Sukamulia', 'deskel' => 'Dasan Lekong'],
            ['no_camat' => '8', 'no_deskel' => '5', 'kecamatan' => 'Sukamulia', 'deskel' => 'Sukamulia'],
            ['no_camat' => '8', 'no_deskel' => '6', 'kecamatan' => 'Sukamulia', 'deskel' => 'Paok Pampang '],
            ['no_camat' => '8', 'no_deskel' => '7', 'kecamatan' => 'Sukamulia', 'deskel' => 'Sukamulia Timur '],
            ['no_camat' => '8', 'no_deskel' => '8', 'kecamatan' => 'Sukamulia', 'deskel' => 'Nyiur Tebel'],
            ['no_camat' => '8', 'no_deskel' => '9', 'kecamatan' => 'Sukamulia', 'deskel' => 'Setanggor Selatan '],
            ['no_camat' => '9', 'no_deskel' => '0', 'kecamatan' => 'Suralaga', 'deskel' => '-'],
            ['no_camat' => '9', 'no_deskel' => '1', 'kecamatan' => 'Suralaga', 'deskel' => 'Anjani'],
            ['no_camat' => '9', 'no_deskel' => '2', 'kecamatan' => 'Suralaga', 'deskel' => 'Tebaban'],
            ['no_camat' => '9', 'no_deskel' => '3', 'kecamatan' => 'Suralaga', 'deskel' => 'Kerongkong'],
            ['no_camat' => '9', 'no_deskel' => '4', 'kecamatan' => 'Suralaga', 'deskel' => 'Bagik Payung'],
            ['no_camat' => '9', 'no_deskel' => '5', 'kecamatan' => 'Suralaga', 'deskel' => 'Suralaga'],
            ['no_camat' => '9', 'no_deskel' => '6', 'kecamatan' => 'Suralaga', 'deskel' => 'Bagik Payung Selatan'],
            ['no_camat' => '9', 'no_deskel' => '7', 'kecamatan' => 'Suralaga', 'deskel' => 'Tumbuh Mulia '],
            ['no_camat' => '9', 'no_deskel' => '8', 'kecamatan' => 'Suralaga', 'deskel' => 'Dasan Borok '],
            ['no_camat' => '9', 'no_deskel' => '9', 'kecamatan' => 'Suralaga', 'deskel' => 'Gerung Permai '],
            ['no_camat' => '9', 'no_deskel' => '10', 'kecamatan' => 'Suralaga', 'deskel' => 'Dames Damai '],
            ['no_camat' => '9', 'no_deskel' => '11', 'kecamatan' => 'Suralaga', 'deskel' => 'Bagik Payung Timur '],
            ['no_camat' => '9', 'no_deskel' => '12', 'kecamatan' => 'Suralaga', 'deskel' => 'Waringin'],
            ['no_camat' => '9', 'no_deskel' => '13', 'kecamatan' => 'Suralaga', 'deskel' => 'Gapuk '],
            ['no_camat' => '9', 'no_deskel' => '14', 'kecamatan' => 'Suralaga', 'deskel' => 'Bintang Rinjani '],
            ['no_camat' => '9', 'no_deskel' => '15', 'kecamatan' => 'Suralaga', 'deskel' => 'Paok Lombok '],
            ['no_camat' => '10', 'no_deskel' => '0', 'kecamatan' => 'Aikmel', 'deskel' => '-'],
            ['no_camat' => '10', 'no_deskel' => '1', 'kecamatan' => 'Aikmel', 'deskel' => 'Aikmel'],
            ['no_camat' => '10', 'no_deskel' => '2', 'kecamatan' => 'Aikmel', 'deskel' => 'Aikmel Utara'],
            ['no_camat' => '10', 'no_deskel' => '3', 'kecamatan' => 'Aikmel', 'deskel' => 'Aikmel Barat '],
            ['no_camat' => '10', 'no_deskel' => '4', 'kecamatan' => 'Aikmel', 'deskel' => 'Aikmel Timur '],
            ['no_camat' => '10', 'no_deskel' => '5', 'kecamatan' => 'Aikmel', 'deskel' => 'Aikprapa '],
            ['no_camat' => '10', 'no_deskel' => '6', 'kecamatan' => 'Aikmel', 'deskel' => 'Bagik Nyaka Santri '],
            ['no_camat' => '10', 'no_deskel' => '7', 'kecamatan' => 'Aikmel', 'deskel' => 'Keroya '],
            ['no_camat' => '10', 'no_deskel' => '8', 'kecamatan' => 'Aikmel', 'deskel' => 'Kembang Kerang'],
            ['no_camat' => '10', 'no_deskel' => '9', 'kecamatan' => 'Aikmel', 'deskel' => 'Kalijaga'],
            ['no_camat' => '10', 'no_deskel' => '10', 'kecamatan' => 'Aikmel', 'deskel' => 'Kalijaga Tengah '],
            ['no_camat' => '10', 'no_deskel' => '11', 'kecamatan' => 'Aikmel', 'deskel' => 'Kembang Kerang Daya '],
            ['no_camat' => '10', 'no_deskel' => '12', 'kecamatan' => 'Aikmel', 'deskel' => 'Kalijaga Timur'],
            ['no_camat' => '10', 'no_deskel' => '13', 'kecamatan' => 'Aikmel', 'deskel' => 'Kalijaga Selatan'],
            ['no_camat' => '10', 'no_deskel' => '14', 'kecamatan' => 'Aikmel', 'deskel' => 'Toya'],
            ['no_camat' => '11', 'no_deskel' => '0', 'kecamatan' => 'Lenek', 'deskel' => '-'],
            ['no_camat' => '11', 'no_deskel' => '1', 'kecamatan' => 'Lenek', 'deskel' => 'Lenek'],
            ['no_camat' => '11', 'no_deskel' => '2', 'kecamatan' => 'Lenek', 'deskel' => 'Lenek Lauk'],
            ['no_camat' => '11', 'no_deskel' => '3', 'kecamatan' => 'Lenek', 'deskel' => 'Lenek Daya'],
            ['no_camat' => '11', 'no_deskel' => '4', 'kecamatan' => 'Lenek', 'deskel' => 'Lenek Baru '],
            ['no_camat' => '11', 'no_deskel' => '5', 'kecamatan' => 'Lenek', 'deskel' => 'Lenek Duren '],
            ['no_camat' => '11', 'no_deskel' => '6', 'kecamatan' => 'Lenek', 'deskel' => 'Lenek Pesiraman '],
            ['no_camat' => '11', 'no_deskel' => '7', 'kecamatan' => 'Lenek', 'deskel' => 'Lenek Kali Bambang '],
            ['no_camat' => '11', 'no_deskel' => '8', 'kecamatan' => 'Lenek', 'deskel' => 'Lenek Ramban Biak '],
            ['no_camat' => '11', 'no_deskel' => '9', 'kecamatan' => 'Lenek', 'deskel' => 'Kalijaga Baru '],
            ['no_camat' => '11', 'no_deskel' => '10', 'kecamatan' => 'Lenek', 'deskel' => 'Sukarema '],
            ['no_camat' => '12', 'no_deskel' => '0', 'kecamatan' => 'Wanasaba', 'deskel' => '-'],
            ['no_camat' => '12', 'no_deskel' => '1', 'kecamatan' => 'Wanasaba', 'deskel' => 'Wanasaba'],
            ['no_camat' => '12', 'no_deskel' => '2', 'kecamatan' => 'Wanasaba', 'deskel' => 'Wanasaba Lauk '],
            ['no_camat' => '12', 'no_deskel' => '3', 'kecamatan' => 'Wanasaba', 'deskel' => 'Wanasaba Daya'],
            ['no_camat' => '12', 'no_deskel' => '4', 'kecamatan' => 'Wanasaba', 'deskel' => 'Karang Baru'],
            ['no_camat' => '12', 'no_deskel' => '5', 'kecamatan' => 'Wanasaba', 'deskel' => 'Karang Baru Timur '],
            ['no_camat' => '12', 'no_deskel' => '6', 'kecamatan' => 'Wanasaba', 'deskel' => 'Jineng '],
            ['no_camat' => '12', 'no_deskel' => '7', 'kecamatan' => 'Wanasaba', 'deskel' => 'Mamben Lauk'],
            ['no_camat' => '12', 'no_deskel' => '8', 'kecamatan' => 'Wanasaba', 'deskel' => 'Mamben Daya'],
            ['no_camat' => '12', 'no_deskel' => '9', 'kecamatan' => 'Wanasaba', 'deskel' => 'Mamben Baru'],
            ['no_camat' => '12', 'no_deskel' => '10', 'kecamatan' => 'Wanasaba', 'deskel' => 'Tembeng Putik'],
            ['no_camat' => '12', 'no_deskel' => '11', 'kecamatan' => 'Wanasaba', 'deskel' => 'Bandok '],
            ['no_camat' => '12', 'no_deskel' => '12', 'kecamatan' => 'Wanasaba', 'deskel' => 'Bebidas'],
            ['no_camat' => '12', 'no_deskel' => '13', 'kecamatan' => 'Wanasaba', 'deskel' => 'Beririjarak '],
            ['no_camat' => '12', 'no_deskel' => '14', 'kecamatan' => 'Wanasaba', 'deskel' => 'Otak Rarangan '],
            ['no_camat' => '13', 'no_deskel' => '0', 'kecamatan' => 'Pringgabaya', 'deskel' => '-'],
            ['no_camat' => '13', 'no_deskel' => '1', 'kecamatan' => 'Pringgabaya', 'deskel' => 'Bagekpapan'],
            ['no_camat' => '13', 'no_deskel' => '2', 'kecamatan' => 'Pringgabaya', 'deskel' => 'Apitaik'],
            ['no_camat' => '13', 'no_deskel' => '3', 'kecamatan' => 'Pringgabaya', 'deskel' => 'Kerumut'],
            ['no_camat' => '13', 'no_deskel' => '4', 'kecamatan' => 'Pringgabaya', 'deskel' => 'Pohgading'],
            ['no_camat' => '13', 'no_deskel' => '5', 'kecamatan' => 'Pringgabaya', 'deskel' => 'Batuyang'],
            ['no_camat' => '13', 'no_deskel' => '6', 'kecamatan' => 'Pringgabaya', 'deskel' => 'Pringgabaya'],
            ['no_camat' => '13', 'no_deskel' => '7', 'kecamatan' => 'Pringgabaya', 'deskel' => 'Labuhan Lombok'],
            ['no_camat' => '13', 'no_deskel' => '8', 'kecamatan' => 'Pringgabaya', 'deskel' => 'Pringgabaya Utara '],
            ['no_camat' => '13', 'no_deskel' => '9', 'kecamatan' => 'Pringgabaya', 'deskel' => 'Pohgading Timur '],
            ['no_camat' => '13', 'no_deskel' => '10', 'kecamatan' => 'Pringgabaya', 'deskel' => 'Teko '],
            ['no_camat' => '13', 'no_deskel' => '11', 'kecamatan' => 'Pringgabaya', 'deskel' => 'Anggaraksa '],
            ['no_camat' => '13', 'no_deskel' => '12', 'kecamatan' => 'Pringgabaya', 'deskel' => 'Tanak Gadang '],
            ['no_camat' => '13', 'no_deskel' => '13', 'kecamatan' => 'Pringgabaya', 'deskel' => 'Gunung Malang'],
            ['no_camat' => '13', 'no_deskel' => '14', 'kecamatan' => 'Pringgabaya', 'deskel' => 'Seruni Mumbul '],
            ['no_camat' => '13', 'no_deskel' => '15', 'kecamatan' => 'Pringgabaya', 'deskel' => 'Telaga Waru '],
            ['no_camat' => '14', 'no_deskel' => '0', 'kecamatan' => 'Suela', 'deskel' => '-'],
            ['no_camat' => '14', 'no_deskel' => '1', 'kecamatan' => 'Suela', 'deskel' => 'Selaparang'],
            ['no_camat' => '14', 'no_deskel' => '2', 'kecamatan' => 'Suela', 'deskel' => 'Ketangga'],
            ['no_camat' => '14', 'no_deskel' => '3', 'kecamatan' => 'Suela', 'deskel' => 'Suntalangu'],
            ['no_camat' => '14', 'no_deskel' => '4', 'kecamatan' => 'Suela', 'deskel' => 'Suela'],
            ['no_camat' => '14', 'no_deskel' => '5', 'kecamatan' => 'Suela', 'deskel' => 'Sapit'],
            ['no_camat' => '14', 'no_deskel' => '6', 'kecamatan' => 'Suela', 'deskel' => 'Perigi'],
            ['no_camat' => '14', 'no_deskel' => '7', 'kecamatan' => 'Suela', 'deskel' => 'Mekar Sari '],
            ['no_camat' => '14', 'no_deskel' => '8', 'kecamatan' => 'Suela', 'deskel' => 'Puncak Jeringo'],
            ['no_camat' => '15', 'no_deskel' => '0', 'kecamatan' => 'Sambelia', 'deskel' => '-'],
            ['no_camat' => '15', 'no_deskel' => '1', 'kecamatan' => 'Sambelia', 'deskel' => 'Obel-obel'],
            ['no_camat' => '15', 'no_deskel' => '2', 'kecamatan' => 'Sambelia', 'deskel' => 'Belanting'],
            ['no_camat' => '15', 'no_deskel' => '3', 'kecamatan' => 'Sambelia', 'deskel' => 'Sambalia'],
            ['no_camat' => '15', 'no_deskel' => '4', 'kecamatan' => 'Sambelia', 'deskel' => 'Labuhan Pandan'],
            ['no_camat' => '15', 'no_deskel' => '5', 'kecamatan' => 'Sambelia', 'deskel' => 'Sugian'],
            ['no_camat' => '15', 'no_deskel' => '6', 'kecamatan' => 'Sambelia', 'deskel' => 'Dara Kunci '],
            ['no_camat' => '15', 'no_deskel' => '7', 'kecamatan' => 'Sambelia', 'deskel' => 'Bagik Manis '],
            ['no_camat' => '15', 'no_deskel' => '8', 'kecamatan' => 'Sambelia', 'deskel' => 'Dadap '],
            ['no_camat' => '15', 'no_deskel' => '9', 'kecamatan' => 'Sambelia', 'deskel' => 'Senanggalih '],
            ['no_camat' => '15', 'no_deskel' => '10', 'kecamatan' => 'Sambelia', 'deskel' => 'Padak Guar '],
            ['no_camat' => '15', 'no_deskel' => '11', 'kecamatan' => 'Sambelia', 'deskel' => 'Madayin '],
            ['no_camat' => '16', 'no_deskel' => '0', 'kecamatan' => 'Sembalun', 'deskel' => '-'],
            ['no_camat' => '16', 'no_deskel' => '1', 'kecamatan' => 'Sembalun', 'deskel' => 'Sembalun Bumbung'],
            ['no_camat' => '16', 'no_deskel' => '2', 'kecamatan' => 'Sembalun', 'deskel' => 'Sembalun Lawang'],
            ['no_camat' => '16', 'no_deskel' => '3', 'kecamatan' => 'Sembalun', 'deskel' => 'Sajang'],
            ['no_camat' => '16', 'no_deskel' => '4', 'kecamatan' => 'Sembalun', 'deskel' => 'Bilok Petung '],
            ['no_camat' => '16', 'no_deskel' => '5', 'kecamatan' => 'Sembalun', 'deskel' => 'Sembalun '],
            ['no_camat' => '16', 'no_deskel' => '6', 'kecamatan' => 'Sembalun', 'deskel' => 'Sembalun Timba Gading'],
            ['no_camat' => '17', 'no_deskel' => '0', 'kecamatan' => 'Sakra', 'deskel' => '-'],
            ['no_camat' => '17', 'no_deskel' => '1', 'kecamatan' => 'Sakra', 'deskel' => 'Suwangi'],
            ['no_camat' => '17', 'no_deskel' => '2', 'kecamatan' => 'Sakra', 'deskel' => 'Sakra'],
            ['no_camat' => '17', 'no_deskel' => '3', 'kecamatan' => 'Sakra', 'deskel' => 'Kabar'],
            ['no_camat' => '17', 'no_deskel' => '4', 'kecamatan' => 'Sakra', 'deskel' => 'Rumbuk'],
            ['no_camat' => '17', 'no_deskel' => '5', 'kecamatan' => 'Sakra', 'deskel' => 'Keselet'],
            ['no_camat' => '17', 'no_deskel' => '6', 'kecamatan' => 'Sakra', 'deskel' => 'Sakra Selatan '],
            ['no_camat' => '17', 'no_deskel' => '7', 'kecamatan' => 'Sakra', 'deskel' => 'Rumbuk Timur '],
            ['no_camat' => '17', 'no_deskel' => '8', 'kecamatan' => 'Sakra', 'deskel' => 'Suwangi Timur '],
            ['no_camat' => '17', 'no_deskel' => '9', 'kecamatan' => 'Sakra', 'deskel' => 'Moyot '],
            ['no_camat' => '17', 'no_deskel' => '10', 'kecamatan' => 'Sakra', 'deskel' => 'Songak '],
            ['no_camat' => '17', 'no_deskel' => '11', 'kecamatan' => 'Sakra', 'deskel' => 'Peresak '],
            ['no_camat' => '17', 'no_deskel' => '12', 'kecamatan' => 'Sakra', 'deskel' => 'Kuang Baru '],
            ['no_camat' => '18', 'no_deskel' => '0', 'kecamatan' => 'Sakra Barat', 'deskel' => '-'],
            ['no_camat' => '18', 'no_deskel' => '1', 'kecamatan' => 'Sakra Barat', 'deskel' => 'Sukarara'],
            ['no_camat' => '18', 'no_deskel' => '2', 'kecamatan' => 'Sakra Barat', 'deskel' => 'Gunung Rajak'],
            ['no_camat' => '18', 'no_deskel' => '3', 'kecamatan' => 'Sakra Barat', 'deskel' => 'Rensing'],
            ['no_camat' => '18', 'no_deskel' => '4', 'kecamatan' => 'Sakra Barat', 'deskel' => 'Bungtiang'],
            ['no_camat' => '18', 'no_deskel' => '5', 'kecamatan' => 'Sakra Barat', 'deskel' => 'Pengkelak Mas'],
            ['no_camat' => '18', 'no_deskel' => '6', 'kecamatan' => 'Sakra Barat', 'deskel' => 'Borok Toyang '],
            ['no_camat' => '18', 'no_deskel' => '7', 'kecamatan' => 'Sakra Barat', 'deskel' => 'Rensing Raya'],
            ['no_camat' => '18', 'no_deskel' => '8', 'kecamatan' => 'Sakra Barat', 'deskel' => 'Pematung '],
            ['no_camat' => '18', 'no_deskel' => '9', 'kecamatan' => 'Sakra Barat', 'deskel' => 'Jero Gunung '],
            ['no_camat' => '18', 'no_deskel' => '10', 'kecamatan' => 'Sakra Barat', 'deskel' => 'Pejaring '],
            ['no_camat' => '18', 'no_deskel' => '11', 'kecamatan' => 'Sakra Barat', 'deskel' => 'Boyemare '],
            ['no_camat' => '18', 'no_deskel' => '12', 'kecamatan' => 'Sakra Barat', 'deskel' => 'Montong Beter'],
            ['no_camat' => '18', 'no_deskel' => '13', 'kecamatan' => 'Sakra Barat', 'deskel' => 'Mengkuru '],
            ['no_camat' => '18', 'no_deskel' => '14', 'kecamatan' => 'Sakra Barat', 'deskel' => 'Gadung Mas '],
            ['no_camat' => '18', 'no_deskel' => '15', 'kecamatan' => 'Sakra Barat', 'deskel' => 'Kembang Ara Sampai'],
            ['no_camat' => '18', 'no_deskel' => '16', 'kecamatan' => 'Sakra Barat', 'deskel' => 'Rensing Bat '],
            ['no_camat' => '18', 'no_deskel' => '17', 'kecamatan' => 'Sakra Barat', 'deskel' => 'Tanak Kaken'],
            ['no_camat' => '18', 'no_deskel' => '18', 'kecamatan' => 'Sakra Barat', 'deskel' => 'Gerisak Semang Geleng '],
            ['no_camat' => '19', 'no_deskel' => '0', 'kecamatan' => 'Sakra Timur', 'deskel' => '-'],
            ['no_camat' => '19', 'no_deskel' => '1', 'kecamatan' => 'Sakra Timur', 'deskel' => 'Gelanggang'],
            ['no_camat' => '19', 'no_deskel' => '2', 'kecamatan' => 'Sakra Timur', 'deskel' => 'Surabaya'],
            ['no_camat' => '19', 'no_deskel' => '3', 'kecamatan' => 'Sakra Timur', 'deskel' => 'Lepak'],
            ['no_camat' => '19', 'no_deskel' => '4', 'kecamatan' => 'Sakra Timur', 'deskel' => 'Gereneng'],
            ['no_camat' => '19', 'no_deskel' => '5', 'kecamatan' => 'Sakra Timur', 'deskel' => 'Montong Tangi'],
            ['no_camat' => '19', 'no_deskel' => '6', 'kecamatan' => 'Sakra Timur', 'deskel' => 'Menceh '],
            ['no_camat' => '19', 'no_deskel' => '7', 'kecamatan' => 'Sakra Timur', 'deskel' => 'Lepak Timur '],
            ['no_camat' => '19', 'no_deskel' => '8', 'kecamatan' => 'Sakra Timur', 'deskel' => 'Surabaya Utara '],
            ['no_camat' => '19', 'no_deskel' => '9', 'kecamatan' => 'Sakra Timur', 'deskel' => 'Gereneng Timur '],
            ['no_camat' => '19', 'no_deskel' => '10', 'kecamatan' => 'Sakra Timur', 'deskel' => 'Lenting '],
            ['no_camat' => '20', 'no_deskel' => '0', 'kecamatan' => 'KeruaK', 'deskel' => '-'],
            ['no_camat' => '20', 'no_deskel' => '1', 'kecamatan' => 'KeruaK', 'deskel' => 'Tanjung Luar'],
            ['no_camat' => '20', 'no_deskel' => '2', 'kecamatan' => 'KeruaK', 'deskel' => 'Pijot'],
            ['no_camat' => '20', 'no_deskel' => '3', 'kecamatan' => 'KeruaK', 'deskel' => 'Selebung Ketangga'],
            ['no_camat' => '20', 'no_deskel' => '4', 'kecamatan' => 'KeruaK', 'deskel' => 'Sepit'],
            ['no_camat' => '20', 'no_deskel' => '5', 'kecamatan' => 'KeruaK', 'deskel' => 'Batu Putik '],
            ['no_camat' => '20', 'no_deskel' => '6', 'kecamatan' => 'KeruaK', 'deskel' => 'Senyiur '],
            ['no_camat' => '20', 'no_deskel' => '7', 'kecamatan' => 'KeruaK', 'deskel' => 'Keruak '],
            ['no_camat' => '20', 'no_deskel' => '8', 'kecamatan' => 'KeruaK', 'deskel' => 'Ketapang Raya '],
            ['no_camat' => '20', 'no_deskel' => '9', 'kecamatan' => 'KeruaK', 'deskel' => 'Pijot Utara '],
            ['no_camat' => '20', 'no_deskel' => '10', 'kecamatan' => 'KeruaK', 'deskel' => 'Dane Rase '],
            ['no_camat' => '20', 'no_deskel' => '11', 'kecamatan' => 'KeruaK', 'deskel' => 'Ketangga Jeraeng '],
            ['no_camat' => '20', 'no_deskel' => '12', 'kecamatan' => 'KeruaK', 'deskel' => 'Mendana Raya'],
            ['no_camat' => '20', 'no_deskel' => '13', 'kecamatan' => 'KeruaK', 'deskel' => 'Setungkeplingsar '],
            ['no_camat' => '20', 'no_deskel' => '14', 'kecamatan' => 'KeruaK', 'deskel' => 'Montong Belai '],
            ['no_camat' => '20', 'no_deskel' => '15', 'kecamatan' => 'KeruaK', 'deskel' => 'Pulau Maringkik '],
            ['no_camat' => '21', 'no_deskel' => '0', 'kecamatan' => 'Jerowaru', 'deskel' => '-'],
            ['no_camat' => '21', 'no_deskel' => '1', 'kecamatan' => 'Jerowaru', 'deskel' => 'Jerowaru'],
            ['no_camat' => '21', 'no_deskel' => '2', 'kecamatan' => 'Jerowaru', 'deskel' => 'Sepapan '],
            ['no_camat' => '21', 'no_deskel' => '3', 'kecamatan' => 'Jerowaru', 'deskel' => 'Pandan Wangi '],
            ['no_camat' => '21', 'no_deskel' => '4', 'kecamatan' => 'Jerowaru', 'deskel' => 'Paremas '],
            ['no_camat' => '21', 'no_deskel' => '5', 'kecamatan' => 'Jerowaru', 'deskel' => 'Sukaraja'],
            ['no_camat' => '21', 'no_deskel' => '6', 'kecamatan' => 'Jerowaru', 'deskel' => 'Wakan '],
            ['no_camat' => '21', 'no_deskel' => '7', 'kecamatan' => 'Jerowaru', 'deskel' => 'Sukadamai '],
            ['no_camat' => '21', 'no_deskel' => '8', 'kecamatan' => 'Jerowaru', 'deskel' => 'Batu Nampar'],
            ['no_camat' => '21', 'no_deskel' => '9', 'kecamatan' => 'Jerowaru', 'deskel' => 'Batunampar Selatan '],
            ['no_camat' => '21', 'no_deskel' => '10', 'kecamatan' => 'Jerowaru', 'deskel' => 'Pene'],
            ['no_camat' => '21', 'no_deskel' => '11', 'kecamatan' => 'Jerowaru', 'deskel' => 'Pemongkang'],
            ['no_camat' => '21', 'no_deskel' => '12', 'kecamatan' => 'Jerowaru', 'deskel' => 'Sekaroh '],
            ['no_camat' => '21', 'no_deskel' => '13', 'kecamatan' => 'Jerowaru', 'deskel' => 'Kwang Rundun'],
            ['no_camat' => '21', 'no_deskel' => '14', 'kecamatan' => 'Jerowaru', 'deskel' => 'Ekas Buana '],
            ['no_camat' => '21', 'no_deskel' => '15', 'kecamatan' => 'Jerowaru', 'deskel' => 'Seriwe'],
        ];

        foreach ($data as $item) {
            Kecamatan::create($item);
        }
    }
}