<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PokokTemuan;

class PokokTemuanSeeder extends Seeder
{
    public function run()
    {
        $data = [
            ['no_pokok' => '01', 'no_subpokok' => '00', 'pokok_temuan' => 'Kejadian Yang Merugikan Negara dan Masyarakat'],
            ['no_pokok' => '01', 'no_subpokok' => '01', 'pokok_temuan' => 'Ketekoran Kas'],
            ['no_pokok' => '01', 'no_subpokok' => '02', 'pokok_temuan' => 'Uang/Barang Negara diambil untuk kepentingan pribadi.'],
            ['no_pokok' => '01', 'no_subpokok' => '03', 'pokok_temuan' => 'Pengeluaran fiktif (pengeluaran tanpa imbalan barang atau jasa bagian Negara).'],
            ['no_pokok' => '01', 'no_subpokok' => '04', 'pokok_temuan' => 'Harga pengadaan/pelaksanaan pekerjaan lebih tinggi dari yang semestinya sehingga perlu ada pengembalian uang.'],
            ['no_pokok' => '01', 'no_subpokok' => '05', 'pokok_temuan' => 'Pengembalian uang muka untuk pekerjaan/pengadaan yang tidak dilaksanakan.'],
            ['no_pokok' => '01', 'no_subpokok' => '06', 'pokok_temuan' => 'Pengembalian uang karena kualitas barang/jasa tidak sesuai kontrak.'],
            ['no_pokok' => '01', 'no_subpokok' => '07', 'pokok_temuan' => 'Pelaksanaan pekerjaan/pengadaan atas barang/jasa yang tidak sesuai kontrak.'],
            ['no_pokok' => '01', 'no_subpokok' => '08', 'pokok_temuan' => 'Tindakan lain pegawai yang menimbulkan kerugian Negara.'],
            ['no_pokok' => '01', 'no_subpokok' => '09', 'pokok_temuan' => 'Kelalaian pegawai yang menimbulkan kerugian Negara.'],
            ['no_pokok' => '01', 'no_subpokok' => '10', 'pokok_temuan' => 'Tuntutan ganti rugi kepada pegawai atau pihak III yang masih harus diselesaikan Pembayarannya (belum dilunasi).'],
            ['no_pokok' => '01', 'no_subpokok' => '11', 'pokok_temuan' => 'Penggunaan dana yang tidak sesuai dengan tujuan/sasaran program.'],
            ['no_pokok' => '01', 'no_subpokok' => '12', 'pokok_temuan' => 'Pungutan yang tidak memiliki dasar hukum yang jelas.'],
            ['no_pokok' => '01', 'no_subpokok' => '13', 'pokok_temuan' => 'Pungutan kepada masyarakat/perusahaan diluar ketentuan.'],
            ['no_pokok' => '01', 'no_subpokok' => '14', 'pokok_temuan' => 'Pemotongan bantuan negara kepada masyarakat.'],
            ['no_pokok' => '01', 'no_subpokok' => '15', 'pokok_temuan' => 'Menghidupkan kembali temuan 10100 yang telah diekstra komptabelkan, tetapi ditindaklanjuti.'],
            ['no_pokok' => '02', 'no_subpokok' => '00', 'pokok_temuan' => 'Kewajiban Penyetoran Kepada Negara'],
            ['no_pokok' => '02', 'no_subpokok' => '01', 'pokok_temuan' => 'Kewajiban Penyetoran Pajak (Pajak, Bea dan Cukai Pendapatan Minyak.'],
            ['no_pokok' => '02', 'no_subpokok' => '02', 'pokok_temuan' => 'Pajak yang telah dipungut oleh Bendaharawan/Badan (sbg Wapu) tetapi belum disetorkan ke Kas Negara sesuai dengan batas waktu yang telah ditetapkan menurut ketentuan yang berlaku.'],
            ['no_pokok' => '02', 'no_subpokok' => '03', 'pokok_temuan' => 'Pajak -Pajak yang masih harus dipungut dan disetorkan ke Kas Negara oleh Bendaharawan / Badan'],
            ['no_pokok' => '02', 'no_subpokok' => '04', 'pokok_temuan' => 'Tunggakan angsuran pajak yang masih harus disetorkan ke Kas Negara.'],
            ['no_pokok' => '02', 'no_subpokok' => '05', 'pokok_temuan' => 'Kewajiban penyetoran pajak daerah.'],
            ['no_pokok' => '02', 'no_subpokok' => '06', 'pokok_temuan' => 'Pajak daerah yang telah dipungut oleh Bendaharawan /Badan (sebagai wajib pungut) tetapi belum disetorkan ke Kas Daerah sesuai dengan batas waktu yang telah ditetapkan menurut ketentuan yang berlaku.'],
            ['no_pokok' => '02', 'no_subpokok' => '07', 'pokok_temuan' => 'Pajak-pajak daerah yang masih harus dipungut dan disetorkan ke Kas Daerah atau Bendaharawan/Badan.'],
            ['no_pokok' => '02', 'no_subpokok' => '08', 'pokok_temuan' => 'Tunggakan angsuran pajak yang masih harus disetorkan ke Kas Daerah.'],
            ['no_pokok' => '02', 'no_subpokok' => '09', 'pokok_temuan' => 'Kewajiban penyetoran ke Kas Negara berupa jaminan lelang, pelaksanaan pekerjaan dan lainnya.'],
            ['no_pokok' => '02', 'no_subpokok' => '10', 'pokok_temuan' => 'Kewajiban penyetoran ke Kas BUMN/BUMD jaminan lelang, pelaksanaan pekerjaan dan lainnya.'],
            ['no_pokok' => '02', 'no_subpokok' => '11', 'pokok_temuan' => 'Denda atas kelambatan pekerjaan/pengadaan barang.'],
            ['no_pokok' => '02', 'no_subpokok' => '12', 'pokok_temuan' => 'Jumlah denda telah ditetapkan tetapi belum disetorkan ke Kas Negara.'],
            ['no_pokok' => '02', 'no_subpokok' => '13', 'pokok_temuan' => 'Jumlah denda masih harus ditetapkan dan disetorkan ke Kas Negara.'],
            ['no_pokok' => '02', 'no_subpokok' => '14', 'pokok_temuan' => 'Denda atas kelambatan pekerjaan/pengadaan barang atas beban anggaran daerah.'],
            ['no_pokok' => '02', 'no_subpokok' => '15', 'pokok_temuan' => 'Jumlah denda telah ditetapkan, tetapi belum disetorkan ke Kas Daerah.'],
            ['no_pokok' => '02', 'no_subpokok' => '16', 'pokok_temuan' => 'Jumlah denda masih harus ditetapkan dan disetorkan ke Kas Daerah.'],
            ['no_pokok' => '02', 'no_subpokok' => '17', 'pokok_temuan' => 'Denda atas kelambatan pekerjaan/pengadaan barang atas beban BUMN/BUMD.'],
            ['no_pokok' => '02', 'no_subpokok' => '18', 'pokok_temuan' => 'Jumlah denda telah ditetapkan, tetapi belum disetorkan ke Kas BUMN/BUMD.'],
            ['no_pokok' => '02', 'no_subpokok' => '19', 'pokok_temuan' => 'Jumlah denda masih harus ditetapkan dan disetorkan ke Kas BUMN/BUMD.'],
            ['no_pokok' => '02', 'no_subpokok' => '20', 'pokok_temuan' => 'Tuntutan ganti rugi kepada pegawai atau pihak ketiga yang masih harus diselesaikan Pembayarannya (belum dilunasi).'],
            ['no_pokok' => '02', 'no_subpokok' => '21', 'pokok_temuan' => 'Sisa anggaran pada akhir tahun anggaran yang tidak dipergunakan lagi dan masih harus disetorkan ke Kas Negara'],
            ['no_pokok' => '02', 'no_subpokok' => '22', 'pokok_temuan' => 'Kewajiban penyetoran bukan pajak berupa tunggakan penyetoran penerimaan bukan pajak pungutan penerimaan lainnya yang menjadi hak Negara.'],
            ['no_pokok' => '02', 'no_subpokok' => '23', 'pokok_temuan' => 'Kewajiban penyetoran lainnya seperti hasil penjualan barang, sewa alat-alat besar, sewa rumah dinas dsb, yang masih harus disetorkan kepada Negara.'],
            ['no_pokok' => '02', 'no_subpokok' => '24', 'pokok_temuan' => 'Barang/jasa tidak sesuai dengan BA atau Kontrak.'],
            ['no_pokok' => '02', 'no_subpokok' => '25', 'pokok_temuan' => 'Menghidupkan kembali temuan 10200 yang telah diekstra komptabelkan, tetapi ditindaklanjuti.'],
            ['no_pokok' => '03', 'no_subpokok' => '00', 'pokok_temuan' => 'Pelanggaran Terhadap Peraturan Peraturan Perundang-undangan'],
            ['no_pokok' => '03', 'no_subpokok' => '01', 'pokok_temuan' => 'Bidang teknis tertentu'],
            ['no_pokok' => '03', 'no_subpokok' => '02', 'pokok_temuan' => 'Bidang Kepegawaian'],
            ['no_pokok' => '03', 'no_subpokok' => '03', 'pokok_temuan' => 'Bidang perlengkapan'],
            ['no_pokok' => '03', 'no_subpokok' => '04', 'pokok_temuan' => 'Pengelolaan Badan Usaha (BUMN/BUMD)'],
            ['no_pokok' => '03', 'no_subpokok' => '05', 'pokok_temuan' => 'Lainnya'],
            ['no_pokok' => '04', 'no_subpokok' => '00', 'pokok_temuan' => 'Pelanggaran Terhadap Prosedur dan Tata Kerja Yang Telah Ditetapkan Berlaku Khusus Bagi Organisasi Yang Bersangkutan'],
            ['no_pokok' => '04', 'no_subpokok' => '01', 'pokok_temuan' => 'Ketentuan-ketentuan intern organisasi objek yang diaudit'],
            ['no_pokok' => '04', 'no_subpokok' => '02', 'pokok_temuan' => 'Ketentuan khusus berlaku bagi organisasi yang bersangkutan.'],
            ['no_pokok' => '04', 'no_subpokok' => '03', 'pokok_temuan' => 'Persekongkolan (Kolusi)'],
            ['no_pokok' => '04', 'no_subpokok' => '04', 'pokok_temuan' => 'Mengutamakan kepentingan kerabat/sahabat (nepotisme)'],
            ['no_pokok' => '05', 'no_subpokok' => '00', 'pokok_temuan' => 'Penyimpangan Dari Ketentuan Pelaksanaan Anggaran'],
            ['no_pokok' => '05', 'no_subpokok' => '01', 'pokok_temuan' => 'Penyimpangan dari Kepres/Perpes Pedoman Pelaksanaan APBN/APBD'],
            ['no_pokok' => '05', 'no_subpokok' => '02', 'pokok_temuan' => 'Penyimpangan dari RKAP atau pedoman pelaksanaan anggaran lainnya.'],
            ['no_pokok' => '05', 'no_subpokok' => '03', 'pokok_temuan' => 'Penyimpangan dari Kepres/Perpes Pedoman Pelaksanaan Anggaran lainnya'],
            ['no_pokok' => '06', 'no_subpokok' => '00', 'pokok_temuan' => 'Hambatan Terhadap Kelancaran Kegiatan'],
            ['no_pokok' => '06', 'no_subpokok' => '01', 'pokok_temuan' => 'Pelaksanaan kegiatan menyimpang dari jadwal.'],
            ['no_pokok' => '06', 'no_subpokok' => '02', 'pokok_temuan' => 'Selesainya kegiatan menyimpang dari jadwal.'],
            ['no_pokok' => '07', 'no_subpokok' => '00', 'pokok_temuan' => 'Hambatan Terhadap Kelancaran Tugas Pokok'],
            ['no_pokok' => '07', 'no_subpokok' => '01', 'pokok_temuan' => 'Penyimpangan dari jadwal waktu selesainya tugas pokok.'],
            ['no_pokok' => '07', 'no_subpokok' => '02', 'pokok_temuan' => 'Tidak diselenggarakannya dengan baik satu atau lebih tugas dan fungsi satuan kerja.'],
            ['no_pokok' => '08', 'no_subpokok' => '00', 'pokok_temuan' => 'Kelemahan Administrasi (Kelemahan Tata Usaha/Akuntansi)'],
            ['no_pokok' => '08', 'no_subpokok' => '01', 'pokok_temuan' => 'Kelemahan administrasi keuangan.'],
            ['no_pokok' => '08', 'no_subpokok' => '02', 'pokok_temuan' => 'Kelemahan dalam pedoman atau sistem pencatatan.'],
            ['no_pokok' => '08', 'no_subpokok' => '03', 'pokok_temuan' => 'Bukti-bukti pencatatan tidak lengkap.'],
            ['no_pokok' => '08', 'no_subpokok' => '04', 'pokok_temuan' => 'Pelaporan tidak ada, tidak sesuai standar, dan tidak dilaksanakan, atau mengalami kelambatan.'],
            ['no_pokok' => '08', 'no_subpokok' => '05', 'pokok_temuan' => 'Penyimpangan dokumen keuangan menyulitkan pencarian kembali.'],
            ['no_pokok' => '08', 'no_subpokok' => '06', 'pokok_temuan' => 'Kelemahan administrasi non keuangan'],
            ['no_pokok' => '08', 'no_subpokok' => '07', 'pokok_temuan' => 'Kelemahan dalam pedoman atau sistem pencatatan.'],
            ['no_pokok' => '08', 'no_subpokok' => '08', 'pokok_temuan' => 'Kelemahan dalam pelaksanaan pencatatan.'],
            ['no_pokok' => '08', 'no_subpokok' => '09', 'pokok_temuan' => 'Bukti-bukti pencatatan tidak lengkap.'],
            ['no_pokok' => '08', 'no_subpokok' => '10', 'pokok_temuan' => 'Pelaporan tidak dilaksanakan, tidak ada atau mengalami kelambatan.'],
            ['no_pokok' => '08', 'no_subpokok' => '11', 'pokok_temuan' => 'Penyimpangan dokumen non keuangan menyulitkan pencarian kembali.'],
            ['no_pokok' => '09', 'no_subpokok' => '00', 'pokok_temuan' => 'Ketidaklancaran Pelayanan Kepada Masyarakat'],
            ['no_pokok' => '09', 'no_subpokok' => '01', 'pokok_temuan' => 'Ketidaklancaran dalam menerbitkan perijinan kepada masyarakat/instansi yang berwenang pada Kementerian/Pemda seperti Ijin Usaha, Ijin Pemakaian Tempat, Ijin Menggunakan Peralatan, Ijin Mengolah atau Menguasai Kekayaan Alam, Ijin Praktek, dsb.'],
            ['no_pokok' => '09', 'no_subpokok' => '02', 'pokok_temuan' => 'Ketidaklancaran aparatur pemerintah dalam memberikan pelayanan sebagai tugas pokoknya kepada masyarakat.'],
            ['no_pokok' => '10', 'no_subpokok' => '00', 'pokok_temuan' => 'Temuan Audit Lainnya'],
            ['no_pokok' => '10', 'no_subpokok' => '01', 'pokok_temuan' => 'Hambatan kelancaran Program Pembangunan.'],
            ['no_pokok' => '10', 'no_subpokok' => '02', 'pokok_temuan' => 'Pelaksanaan tugas belum efisien.'],
            ['no_pokok' => '10', 'no_subpokok' => '03', 'pokok_temuan' => 'Pelaksanaan pengadaan sumber daya belum hemat.'],
            ['no_pokok' => '10', 'no_subpokok' => '04', 'pokok_temuan' => 'Pencapaian tujuan belum efektif.'],
            ['no_pokok' => '10', 'no_subpokok' => '05', 'pokok_temuan' => 'Produktivitas masih rendah.'],
            ['no_pokok' => '10', 'no_subpokok' => '06', 'pokok_temuan' => 'Temuan Lainnya'],
        ];

        foreach ($data as $item) {
            PokokTemuan::create($item);
        }
    }
}